In [ ]:
# Import the packages that we will be using
import pandas as pd

In [ ]:
# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/MyDrive/Colab Notebooks"

else:
    # Define path del proyecto
    Ruta            = ""

Mounted at /content/drive

In [ ]:
# Dataset url
url= "/content/drive/MyDrive/Colab Notebooks/cartwheel.csv"


# Load the dataset
df = pd.read_csv(url)

In [ ]:
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [ ]:
# Mostrar el número de filas y columnas de los datos
num_filas, num_columnas = df.shape
print(f"{num_filas} filas y {num_columnas} columnas.")

# Mostrar las primeras 5 filas del DataFrame
print("\nPrimeras filas del dataset:")
df.head()

52 filas y 12 columnas.

Primeras filas del dataset:

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [ ]:
df.tail()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [ ]:
df.columns

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

In [ ]:
df.dtypes

In [ ]:
df.describe()

In [ ]:
df["Age"].dropna().describe()  # Para la columna "Age"
df["Wingspan"].dropna().describe()  # Para la columna "Wingspan"

# How to write a data frame to a File

To save a file with your data simply use the `to_csv` attribute

Examples:
- df.to_csv('myDataFrame.csv')
- df.to_csv('myDataFrame.csv', sep='\t')

In [ ]:
df.to_csv('myDataFrame.csv', index=False)  # Guarda el DataFrame sin incluir el índice

In [ ]:
df.to_csv('myDataFrame.csv', sep='\t', index=False)

# Rename columns

To change the name of a colum use the `rename` attribute

Example:

df = df.rename(columns={"Age": "Edad"})

df.head()

In [ ]:
df = df.rename(columns={"Age": "Edad", "Wingspan": "Envergadura"})  # Cambiar nombres de columnas
df.head()  # Verificar cambios

In [ ]:
df.columns = ["Columna1", "Columna2", "Columna3"]  # Ajusta según el número de columnas

# Selection of colums

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent observations or samples and the columns represent variables.  One common manipulation of a data frame is to extract the data for one case or for one variable.  There are several ways to do this, as shown below.

To extract all the values for one column (variable), use one of the following alternatives.

In [ ]:
a = df.Age  # Acceder como atributo

# Slicing a data set

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent cases and the columns represent variables.  One common manipulation of a data frame is to extract the data for one observation or for one variable.  There are several ways to do this, as shown below.

Lets say we would like to splice our data frame and select only specific portions of our data.  There are three different ways of doing so.

1. .loc()
2. .iloc()
3. .ix()

We will cover the .loc() and .iloc() splicing functions.

In [ ]:
# Return all observations of CWDistance
df.loc[:,"CWDistance"]

# Return a subset of observations of CWDistance
df.loc[:9, "CWDistance"]

# Select all rows for multiple columns, ["Gender", "GenderGroup"]
df.loc[:,["Gender", "GenderGroup"]]

# Select multiple columns, ["Gender", "GenderGroup"]me
keep = ['Gender', 'GenderGroup']
df_gender = df[keep]

# Select few rows for multiple columns, ["CWDistance", "Height", "Wingspan"]
df.loc[4:9, ["CWDistance", "Height", "Wingspan"]]

# Select range of rows for all columns
df.loc[10:15,:]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6

In [ ]:
# .
df.iloc[:, :4]

# .
df.iloc[:4, :]

# .
df.iloc[:, 3:7]

# .
df.iloc[4:8, 2:4]

# This is incorrect:
df.iloc[1:5, ["Gender", "GenderGroup"]]

# Get unique existing values

List unique values in the one of the columns

df.Gender.unique()

In [ ]:
# Listar valores únicos en la columna "Gender"
print("Valores únicos en Gender:")
print(df["Gender"].unique())

# Contar valores en la columna "GenderGroup"
print("\nConteo de valores en GenderGroup:")
print(df["GenderGroup"].value_counts())

Valores únicos en Gender:
['F' 'M']

Conteo de valores en GenderGroup:
GenderGroup
1    26
2    26
Name: count, dtype: int64

# Filter, Sort and Groupby

In [ ]:
df_filtered = df[df["Height"] >= 70]
df_filtered.head()  # Mostrar las primeras filas del resultado

In [ ]:
# Ordenar por la columna "Height" en orden ascendente (menor a mayor)
df_sorted_asc = df.sort_values("Height")
print(df_sorted_asc.head())

# Ordenar por la columna "Height" en orden descendente (mayor a menor)
df_sorted_desc = df.sort_values("Height", ascending=False)
print(df_sorted_desc.head())

# Ordenar por múltiples columnas: primero "Age" ascendente, luego "Height" descendente
df_sorted_multi = df.sort_values(["Age", "Height"], ascending=[True, False])
df_sorted_multi.head()

In [ ]:
df_grouped = df.groupby("Gender").mean()  # Agrupar por "Gender" y calcular la media
df_grouped

In [ ]:
df.groupby(['Gender']).size()

df.groupby(['Gender','GenderGroup']).size()

# Data Cleaning: handle with missing data

Before getting started to work with your data, it's a good practice to observe it thoroughly to identify missing values and handle them accordingly.

When reading a dataset using Pandas, there is a set of values including 'NA', 'NULL', and 'NaN' that are taken by default to represent a missing value.  The full list of default missing value codes is in the '`read_csv`' documentation [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).  This document also explains how to change the way that '`read_csv`' decides whether a variable's value is missing.

Pandas has functions called `isnull` and `notnull` that can be used to identify where the missing and non-missing values are located in a data frame.  

Below we use these functions to count the number of missing and non-missing values in each variable of the datasetr.

In [ ]:
# Contar los valores faltantes en cada columna
missing_values = df.isnull().sum()
print("Valores faltantes por columna:")
print(missing_values)

# Contar los valores no faltantes en cada columna
non_missing_values = df.notnull().sum()
print("\nValores no faltantes por columna:")
print(non_missing_values)

In [ ]:
df_cleaned = df.dropna()

In [ ]:
df_cleaned = df.dropna(axis=1)

In [ ]:
df_filled = df.fillna(0)

In [ ]:
df.isnull().sum()
df.notnull().sum()

Now we use these functions to count the number of missing and non-missing values in a single variable in the dataset

print( df.Height.notnull().sum() )

print( pd.isnull(df.Height).sum() )

In [ ]:
print( df.Height.notnull().sum() )
print( pd.isnull(df.Height).sum() )

In [ ]:
# Extract all non-missing values of one of the columns into a new variable
x = df.Age.dropna().describe()
x.describe()

# Add and eliminate columns

In some cases it is useful to create or eiminate new columns

In [ ]:
df.head()

In [ ]:
# Add a new column with new data

# Create a column data
NewColumnData = df.Age/df.Age

# Insert that column in the data frame
df.insert(12, "ColumnInserted", NewColumnData, True)

df.head()

In [ ]:
# # Eliminate inserted column
df.drop("ColumnInserted", axis=1, inplace = True)
df.drop(columns=['ColumnInserted'], inplace = True)
# # Remove three columns as index base
df.drop(df.columns[[12]], axis = 1, inplace = True)
df.head()

In [ ]:
# # Add new column derived from existing columns
# # The new column is a function of another column
df["AgeInMonths"] = df["Age"] * 12
df.head()

In [ ]:
 # Eliminate inserted column
df.drop("AgeInMonths", axis=1, inplace = True)
df.head()

In [ ]:
# Add a new column with text labels reflecting the code's meaning
df["GenderGroupNew"] = df.GenderGroup.replace({1: "Female", 2: "Male"})
# Show the first 5 rows of the created data frame

In [ ]:
## Eliminate inserted column
df.drop("GenderGroupNew", axis=1, inplace = True)
df.drop(['GenderGroupNew'],vaxis='columns',vinplace=True)

In [ ]:
## Add a new column with strata based on these cut points
## Create a column data
NewColumnData = df.Age/df.Age
## Insert that column in the data frame
df.insert(1, "ColumnStrata", NewColumnData, True)
#
df["ColumnStrata"] = pd.cut(df.Height, [60., 63., 66., 69., 72., 75., 78.])
#
## Show the first 5 rows of the created data frame
df.head()

In [ ]:
## Eliminate inserted column
df.drop("ColumnStrata", axis=1, inplace = True)
#
df.head()

In [ ]:
# Drop several "unused" columns
vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
df.drop(vars, axis=1, inplace = True)

# Add and eliminate rows

In some cases it is requiered to add new observations (rows) to the data set

In [ ]:
df.tail()

In [ ]:
# Crear una nueva fila con valores específicos
new_row = [26, 24, 'F', 1, 'Y', 1, 66, 'NaN', 68, 'N', 0, 3]

# Agregar la fila al DataFrame
df.loc[len(df.index)] = new_row

# Verificar que la fila fue añadida
df.tail()

In [ ]:
# Eliminar la fila con índice 28 (ajustar según corresponda)
df.drop(28, inplace=True)

# Verificar que la fila fue eliminada
df.tail()

# Cleaning your data: drop out unused columns and/or drop out rows with any missing values

In [ ]:
# Drop unused columns
vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
df.drop(vars, axis=1, inplace = True)

#vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars]

# Drop rows with any missing values
df = df.dropna()

# Drop unused columns and drop rows with any missing values
vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars].dropna()
df