# Undertanding the cartwheel data set

The notebook aims to undertand the content of the cartwheel data set.


## Acknowledgments

- Data from https://www.coursera.org/ from the course "Understanding and Visualizing Data with Python" by University of Michigan

# Cartwheel data set

1. A cartwheel

![cartwheel1.png](https://drive.google.com/uc?export=view&id=1h6CbMZX9wtRIbxpREgHSLY5IKTEqq6l6)




2. The dataset description
    - The dataset used here is an extension from the original cartwheel dataset from cursera
    - Total numer of observations: 28
    - Many observations/measurements/recordings of the characteristics/attributes/variables of cartwheel executions
    - Variables: Age, Gender, GenderGroup, Glasses, GlassesGroup, Height, Wingspan, CWDistance, ... (X variables)

# Importing and inspecting the data

In [1]:
# Define where you are running the code: colab or local
RunInColab          =  False     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

else:
    # Define path del proyecto
    Ruta            = ""

In [8]:
# Import the packages that we will be using
import numpy as np             
import matplotlib.pyplot as plt     
import pandas as pd                 

# Dataset url
data_path = "../../NotebooksProfessor/cartwheel.csv"

# Load the dataset
df = pd.read_csv(data_path)

In [9]:
# Print the dataset
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

In [13]:
# Print the number of rows
rows = df.shape[0]
rows

52

In [15]:
# Print the number of columns
df.shape[1]

12

# Data types

# Activity: work with the iris dataset

1. Load the iris.csv file in your computer and understand the dataset


2. How many observations (rows) are in total?


3. How many variables (columns) are in total? What do they represent?


4. How many observations are for each type of flower?


5. What is the type of data for each variable?


6. What are the units of each variable?

In [42]:
from sklearn.datasets import load_iris

# 1. Load dataset
iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['species'] = iris.target
# Name columns
df['species'] = df['species'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

In [43]:

# Display the first 5 rows of the dataset
print("First 5 rows of the dataset:")
print(df.head())

# 2. How many observations (rows) are in total?
rows , cols = df.shape
print(f"\nTotal number of observations (rows): {rows}")

First 5 rows of the dataset:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

  species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

Total number of observations (rows): 150

In [ ]:
# 3. How many variables (columns) are in total? What do they represent?
print(f"\nTotal number of variables (columns): {cols}")
print(f"\nColumn names and their representation:")

df.columns

Total number of variables (columns): 5

Column names and their representation:

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'species'],
      dtype='object')

In [45]:
# 4. How many observations are for each type of flower?
flower_counts = df['species'].value_counts()
print(f"\nNumber of observations for each type of flower:")
print(flower_counts)

Number of observations for each type of flower:
species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [ ]:
# 5 and 6. What is the type of data for each variable and their units?
data_types = df.dtypes
print(f"\nData type for each variable:")
print(data_types)

Data type for each variable:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species               object
dtype: object