# Data management using Pandas

**Data management** is a crucial component to statistical analysis and data science work.

This notebook will show you how to import, view, undertand, and manage your data using the [Pandas](http://pandas.pydata.org) data processing library, i.e., the notebook will demonstrates how to read a dataset into Python, and obtain a basic understanding of its content.

Note that **Python** by itself is a general-purpose programming language and does not provide high-level data processing capabilities.  The **Pandas** library was developed to meet this need. **Pandas** is the most popular Python library for data manipulation, and we will use it extensively in this course. **Pandas** provides high-performance, easy-to-use data structures and data analysis tools.

The main data structure that **Pandas** works with is called a **Data Frame**. This is a two-dimensional table of data in which the rows typically
represent cases and the columns represent variables (e.g. data used in this tutorial).  Pandas also has a one-dimensional data structure called a **Series** that we will encounter when accesing a single column of a Data Frame.

Pandas has a variety of functions named `read_xxx` for reading data in different formats.  Right now we will focus on reading `csv` files, which stands for comma-separated values. However the other file formats include `excel`, `json`, and `sql`.

There are many other options to `read_csv` that are very useful.  For example, you would use the option `sep='\t'` instead of the default `sep=','` if the fields of your data file are delimited by tabs instead of commas.  See [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) for the full documentation for `read_csv`.


## Acknowledgments

- The dataset used in this tutorial is from https://www.coursera.org/ from the course "Understanding and Visualizing Data with Python" by University of Michigan

# Importing libraries

In [5]:
# Import the packages that we will be using
import pandas as pd
import seaborn as sn
import numpy as np
import matplotlib.pyplot as plt

# Importing data

In [5]:
# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/My Drive/TC1002S/NotebooksProfessor/"

else:
    # Define path del proyecto
    Ruta            = "nop"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [11]:
# url string that hosts our .csv file
url = Ruta + "cartwheel.csv"
print(url)

# Read the .csv file and store it as a pandas Data Frame

df = pd.read_csv(url)

/content/drive/My Drive/TC1002S/NotebooksProfessor/cartwheel.csv

If we want to print the information about th output object type we would simply type the following: type(df)

In [12]:
type(df)

pandas.core.frame.DataFrame

# Exploring the content of the data set

Use the `shape` method to determine the numbers of rows and columns in a data frame. This can be used to confirm that we have actually obtained the data the we are expecting.

Based on what we see below, the data set being read here has $N_r$ rows, corresponding to $N_r$ observations, and $N_c$ columns, corresponding to $N_c$ variables in this particular data file.

In [18]:
s = df.shape
print(s)
Nr,Nc = df.shape
print(f"El número de filas es {Nr}, y el número de columnas es {Nc}")

(52, 12)
El número de filas es 52, y el número de columnas es 12

If we want to show the entire data frame we would simply write the following:

In [17]:
df

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10

As you can see, we have a 2-Dimensional object where each row is an independent observation and each coloum is a variable.

Now, use the the `head()` function to show the first 5 rows of our data frame

In [24]:
print(df.head(5))

   ID   Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
0   1  56.0      F            1       Y             1    62.0      61.0
1   2  26.0      F            1       Y             1    62.0      60.0
2   3  33.0      F            1       Y             1    66.0      64.0
3   4  39.0      F            1       N             0    64.0      63.0
4   5  27.0      M            2       N             0    73.0      75.0

   CWDistance Complete  CompleteGroup  Score
0          79        Y            1.0      7
1          70        Y            1.0      8
2          85        Y            1.0      7
3          87        Y            1.0     10
4          72        N            0.0      4

Also, you can use the the `tail()` function to show the last 5 rows of our data frame

In [25]:
print(df.tail(5))

    ID   Age Gender  GenderGroup Glasses  GlassesGroup  Height  Wingspan  \
47  48  24.0      M            2       N             0    79.5      75.0
48  49  28.0      M            2       N             0    77.8      76.0
49  50  30.0      F            1       N             0    74.6       NaN
50  51   NaN      M            2       N             0    71.0      70.0
51  52  27.0      M            2       N             0     NaN      71.5

    CWDistance Complete  CompleteGroup  Score
47          82        N            0.0      8
48          99        Y            1.0      9
49          71        Y            1.0      9
50         101        Y            NaN      8
51         103        Y            1.0     10

The columns in a Pandas data frame have names, to see the names, use the `columns` method:

To gather more information regarding the data, we can view the column names with the following function:

In [34]:
print(df.columns)

Index(['ID', 'Age', 'Gender', 'GenderGroup', 'Glasses', 'GlassesGroup',
       'Height', 'Wingspan', 'CWDistance', 'Complete', 'CompleteGroup',
       'Score'],
      dtype='object')

Be aware that every variable in a Pandas data frame has a data type.  There are many different data types, but most commonly you will encounter floating point values (real numbers), integers, strings (text), and date/time values.  When Pandas reads a text/csv file, it guesses the data types based on what it sees in the first few rows of the data file.  Usually it selects an appropriate type, but occasionally it does not.  To confirm that the data types are consistent with what the variables represent, inspect the `dtypes` attribute of the data frame.

In [35]:
print(df.dtypes)

ID                 int64
Age              float64
Gender            object
GenderGroup        int64
Glasses           object
GlassesGroup       int64
Height           float64
Wingspan         float64
CWDistance         int64
Complete          object
CompleteGroup    float64
Score              int64
dtype: object

Summary statistics, which include things like the mean, min, and max of the data, can be useful to get a feel for how large some of the variables are and what variables may be the most important.

In [48]:
# Summary statistics for the quantitative variables
print(df.describe())

              ID        Age  GenderGroup  GlassesGroup     Height   Wingspan  \
count  52.000000  51.000000    52.000000     52.000000  51.000000  51.000000
mean   26.500000  28.411765     1.500000      0.500000  68.971569  67.313725
std    15.154757   5.755611     0.504878      0.504878   5.303812   5.624021
min     1.000000  22.000000     1.000000      0.000000  61.500000  57.500000
25%    13.750000  25.000000     1.000000      0.000000  64.500000  63.000000
50%    26.500000  27.000000     1.500000      0.500000  69.000000  66.000000
75%    39.250000  30.000000     2.000000      1.000000  73.000000  72.000000
max    52.000000  56.000000     2.000000      1.000000  79.500000  76.000000

       CWDistance  CompleteGroup      Score
count   52.000000      51.000000  52.000000
mean    85.576923       0.843137   7.173077
std     14.353173       0.367290   2.211566
min     63.000000       0.000000   2.000000
25%     72.000000       1.000000   6.000000
50%     85.000000       1.000000   8.000000
75%     96.500000       1.000000   9.000000
max    115.000000       1.000000  10.000000

In [46]:
# Drop observations with NaN values
print(df.Age.dropna().describe())
print(df.Wingspan.dropna().describe())

count    51.000000
mean     28.411765
std       5.755611
min      22.000000
25%      25.000000
50%      27.000000
75%      30.000000
max      56.000000
Name: Age, dtype: float64
count    51.000000
mean     67.313725
std       5.624021
min      57.500000
25%      63.000000
50%      66.000000
75%      72.000000
max      76.000000
Name: Wingspan, dtype: float64

It is also possible to get statistics on the entire data frame or a column as follows

- `df.mean()` Returns the mean of all columns
- `df.corr()` Returns the correlation between columns in a data frame
- `df.count()` Returns the number of non-null values in each data frame column
- `df.max()` Returns the highest value in each column
- `df.min()` Returns the lowest value in each column
- `df.median()` Returns the median of each column
- `df.std()` Returns the standard deviation of each column

In [51]:
df.mean(numeric_only=True)

ID               26.500000
Age              28.411765
GenderGroup       1.500000
GlassesGroup      0.500000
Height           68.971569
Wingspan         67.313725
CWDistance       85.576923
CompleteGroup     0.843137
Score             7.173077
dtype: float64

In [52]:
df.corr(numeric_only=True)

,ID,Age,GenderGroup,GlassesGroup,Height,Wingspan,CWDistance,CompleteGroup,Score
ID,1.000000,-0.139088,0.066630,-0.184513,0.313570,0.272402,0.120251,0.110208,0.223190
Age,-0.139088,1.000000,-0.263563,0.153441,-0.321105,-0.250976,-0.030501,0.229843,0.317358
GenderGroup,0.066630,-0.263563,1.000000,-0.230769,0.731284,0.763129,0.265168,-0.224166,-0.272192
GlassesGroup,-0.184513,0.153441,-0.230769,1.000000,-0.251782,-0.212414,-0.075762,0.116313,-0.149266
Height,0.313570,-0.321105,0.731284,-0.251782,1.000000,0.941516,0.315947,-0.242616,-0.042706
Wingspan,0.272402,-0.250976,0.763129,-0.212414,0.941516,1.000000,0.326148,-0.198542,-0.044400
CWDistance,0.120251,-0.030501,0.265168,-0.075762,0.315947,0.326148,1.000000,0.175570,0.368652
CompleteGroup,0.110208,0.229843,-0.224166,0.116313,-0.242616,-0.198542,0.175570,1.000000,0.372424
Score,0.223190,0.317358,-0.272192,-0.149266,-0.042706,-0.044400,0.368652,0.372424,1.000000

In [53]:
df.count(numeric_only=True)

ID               52
Age              51
GenderGroup      52
GlassesGroup     52
Height           51
Wingspan         51
CWDistance       52
CompleteGroup    51
Score            52
dtype: int64

In [54]:
df.max(numeric_only=True)

ID                52.0
Age               56.0
GenderGroup        2.0
GlassesGroup       1.0
Height            79.5
Wingspan          76.0
CWDistance       115.0
CompleteGroup      1.0
Score             10.0
dtype: float64

In [55]:
df.min(numeric_only=True)

ID                1.0
Age              22.0
GenderGroup       1.0
GlassesGroup      0.0
Height           61.5
Wingspan         57.5
CWDistance       63.0
CompleteGroup     0.0
Score             2.0
dtype: float64

In [56]:
df.median(numeric_only=True)

ID               26.5
Age              27.0
GenderGroup       1.5
GlassesGroup      0.5
Height           69.0
Wingspan         66.0
CWDistance       85.0
CompleteGroup     1.0
Score             8.0
dtype: float64

In [57]:
df.std(numeric_only=True)

ID               15.154757
Age               5.755611
GenderGroup       0.504878
GlassesGroup      0.504878
Height            5.303812
Wingspan          5.624021
CWDistance       14.353173
CompleteGroup     0.367290
Score             2.211566
dtype: float64

# How to write a data frame to a File

To save a file with your data simply use the `to_csv` attribute

Examples:
- df.to_csv('myDataFrame.csv')
- df.to_csv('myDataFrame.csv', sep='\t')

In [ ]:
df.to_csv('myDataFrame.csv')
df

# Rename columns

To change the name of a colum use the `rename` attribute

Example:

df = df.rename(columns={"Age": "Edad"})

df.head()

In [63]:
df = df.rename(columns={"Age": "Edad"})

df.head(5)

,ID,Edad,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [64]:
# Back to the original name
df = df.rename(columns={"Edad": "Age"})

df.head(5)

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

# Selection of colums

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent observations or samples and the columns represent variables.  One common manipulation of a data frame is to extract the data for one case or for one variable.  There are several ways to do this, as shown below.

To extract all the values for one column (variable), use one of the following alternatives.

In [77]:
a = df.Age
b = df["Age"]
c = df.loc[:, "Age"]
d = df.iloc[:, 1]

print(a)
#print(b)
#print(c)
#print(d)
print("\n\n")
df[["Gender", "GenderGroup"]]

0     56.0
1     26.0
2     33.0
3     39.0
4     27.0
5     24.0
6     28.0
7     22.0
8     29.0
9     33.0
10    30.0
11    28.0
12    25.0
13    23.0
14    31.0
15    26.0
16    26.0
17    27.0
18    23.0
19    24.0
20    23.0
21    29.0
22    25.0
23    26.0
24    23.0
25    28.0
26    24.0
27    25.0
28    32.0
29    38.0
30    27.0
31    33.0
32    38.0
33    27.0
34    24.0
35    27.0
36    25.0
37    26.0
38    31.0
39    30.0
40    23.0
41    26.0
42    28.0
43    26.0
44    30.0
45    39.0
46    27.0
47    24.0
48    28.0
49    30.0
50     NaN
51    27.0
Name: Age, dtype: float64

   Gender  GenderGroup
0       F            1
1       F            1
2       F            1
3       F            1
4       M            2
5       M            2
6       M            2
7       F            1
8       M            2
9       F            1
10      M            2
11      F            1
12      F            1
13      F            1
14      M            2
15      M            2
16      F            1
17      M            2
18      M            2
19      F            1
20      M            2
21      M            2
22      M            2
23      M            2
24      F            1
25      M            2
26      M            2
27      M            2
28      F            1
29      F            1
30      F            1
31      F            1
32      F            1
33      M            2
34      F            1
35      M            2
36      F            1
37      F            1
38      M            2
39      M            2
40      F            1
41      M            2
42      F            1
43      F            1
44      F            1
45      F            1
46      M            2
47      M            2
48      M            2
49      F            1
50      M            2
51      M            2

# Slicing a data set

As discussed above, a Pandas data frame is a rectangular data table, in which the rows represent cases and the columns represent variables.  One common manipulation of a data frame is to extract the data for one observation or for one variable.  There are several ways to do this, as shown below.

Lets say we would like to splice our data frame and select only specific portions of our data.  There are three different ways of doing so.

1. .loc()
2. .iloc()
3. .ix()

We will cover the .loc() and .iloc() splicing functions.

The attibute **.loc()** uses labels/column names, in specific, it takes two single/list/range operator separated by ',', the first one indicates the rows and the second one indicates columns.

In [82]:
# Return all observations of CWDistance
df.loc[:,"CWDistance"]

# Return a subset of observations of CWDistance
df.loc[:9, "CWDistance"]

# Select all rows for multiple columns, ["Gender", "GenderGroup"]
df.loc[:,["Gender", "GenderGroup"]]

# Select multiple columns, ["Gender", "GenderGroup"]me
keep = ['Gender', 'GenderGroup']
df_gender = df[keep]

# Select few rows for multiple columns, ["CWDistance", "Height", "Wingspan"]
df.loc[4:9, ["CWDistance", "Height", "Wingspan"]]

# Select range of rows for all columns
df.loc[10:15,:]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6

The attribute **iloc()** is an integer based slicing.

In [88]:
# .
#df.iloc[:, :4]

# .
#df.iloc[:4, :]

# .
#df.iloc[:, 3:7]

# .
df.iloc[4:9, 2:4]

# This is incorrect:
#df.iloc[1:5, ["Gender", "GenderGroup"]]

  Gender  GenderGroup
4      M            2
5      M            2
6      M            2
7      F            1
8      M            2

# Get unique existing values

List unique values in the one of the columns

df.Gender.unique()

In [90]:
# List unique values in the df['Gender'] column
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [95]:
# Lets explore df["GenderGroup] as well
print(df["GenderGroup"].unique())
print(df.GenderGroup.unique())

[1 2]
[1 2]

# Filter, Sort and Groupby

With **Filter** you can use different conditions to filter columns. For example, df[df[year] > 1984] would give you only the column year is greater than 1984. You can use & (and) or | (or) to add different conditions to your filtering. This is also called boolean filtering.

df[df["Height"] >= 70]

In [96]:
df[df["Height"] >= 70]

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4
5,6,24.0,M,2,N,0,75.0,71.0,81,N,0.0,3
6,7,28.0,M,2,N,0,75.0,76.0,107,Y,1.0,10
8,9,29.0,M,2,Y,1,74.0,73.0,106,N,0.0,5
14,15,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
15,16,26.0,M,2,Y,1,71.0,72.0,115,Y,1.0,6
18,19,23.0,M,2,Y,1,70.0,69.0,64,Y,1.0,3
21,22,29.0,M,2,N,0,71.0,70.0,101,Y,1.0,8
22,23,25.0,M,2,N,0,70.0,68.0,82,Y,1.0,4
25,26,28.0,M,2,N,0,75.0,76.0,111,Y,1.0,10
26,27,24.0,M,2,N,0,78.4,71.0,92,Y,1.0,7
27,28,25.0,M,2,Y,1,76.0,73.0,107,Y,1.0,8
33,34,27.0,M,2,N,0,77.0,75.0,100,Y,1.0,8
38,39,31.0,M,2,Y,1,73.0,74.0,72,Y,1.0,9
40,41,23.0,F,1,N,0,70.4,71.0,66,Y,1.0,4
41,42,26.0,M,2,Y,1,73.5,72.0,115,Y,1.0,6
42,43,28.0,F,1,Y,1,72.5,72.0,81,Y,1.0,10
43,44,26.0,F,1,Y,1,72.0,72.0,92,Y,1.0,8
46,47,27.0,M,2,N,0,78.0,75.0,72,N,0.0,7
47,48,24.0,M,2,N,0,79.5,75.0,82,N,0.0,8
48,49,28.0,M,2,N,0,77.8,76.0,99,Y,1.0,9
49,50,30.0,F,1,N,0,74.6,NaN,71,Y,1.0,9
50,51,NaN,M,2,N,0,71.0,70.0,101,Y,NaN,8

With **Sort** is possible to sort values in a certain column in an ascending order using `df.sort_values("ColumnName")` or in descending order using `df.sort_values(ColumnName, ascending=False)`.

Furthermore, it’s possible to sort values by Column1Name in ascending order then Column2Name in descending order by using `df.sort_values([Column1Name,Column2Name],ascending=[True,False])`


df.sort_values("Height")
#df.sort_values("Height",ascending=False)

In [105]:
df.sort_values(["Age","Height"],ascending=[True,False])

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
7,8,22.0,F,1,N,0,65.00,62.0,98,Y,1.0,9
40,41,23.0,F,1,N,0,70.40,71.0,66,Y,1.0,4
18,19,23.0,M,2,Y,1,70.00,69.0,64,Y,1.0,3
20,21,23.0,M,2,Y,1,69.00,67.0,66,N,0.0,2
24,25,23.0,F,1,Y,1,65.00,63.0,67,N,0.0,3
13,14,23.0,F,1,N,0,61.50,57.5,66,Y,1.0,4
47,48,24.0,M,2,N,0,79.50,75.0,82,N,0.0,8
26,27,24.0,M,2,N,0,78.40,71.0,92,Y,1.0,7
5,6,24.0,M,2,N,0,75.00,71.0,81,N,0.0,3
19,20,24.0,F,1,Y,1,68.00,66.0,85,Y,1.0,8
34,35,24.0,F,1,N,0,67.80,62.0,98,Y,1.0,9
27,28,25.0,M,2,Y,1,76.00,73.0,107,Y,1.0,8
22,23,25.0,M,2,N,0,70.00,68.0,82,Y,1.0,4
12,13,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
36,37,25.0,F,1,Y,1,65.00,64.5,92,Y,1.0,6
41,42,26.0,M,2,Y,1,73.50,72.0,115,Y,1.0,6
43,44,26.0,F,1,Y,1,72.00,72.0,92,Y,1.0,8
15,16,26.0,M,2,Y,1,71.00,72.0,115,Y,1.0,6
23,24,26.0,M,2,N,0,69.00,71.0,63,Y,1.0,5
1,2,26.0,F,1,Y,1,62.00,60.0,70,Y,1.0,8
16,17,26.0,F,1,N,0,61.50,59.5,90,N,0.0,10
37,38,26.0,F,1,N,0,61.50,59.5,90,Y,1.0,9
46,47,27.0,M,2,N,0,78.00,75.0,72,N,0.0,7
33,34,27.0,M,2,N,0,77.00,75.0,100,Y,1.0,8
4,5,27.0,M,2,N,0,73.00,75.0,72,N,0.0,4
35,36,27.0,M,2,N,0,68.00,66.0,74,Y,1.0,5
17,18,27.0,M,2,N,0,66.00,66.0,74,Y,1.0,5
30,31,27.0,F,1,Y,1,62.00,60.0,72,Y,1.0,8
51,52,27.0,M,2,N,0,NaN,71.5,103,Y,1.0,10
48,49,28.0,M,2,N,0,77.80,76.0,99,Y,1.0,9
6,7,28.0,M,2,N,0,75.00,76.0,107,Y,1.0,10
25,26,28.0,M,2,N,0,75.00,76.0,111,Y,1.0,10
42,43,28.0,F,1,Y,1,72.50,72.0,81,Y,1.0,10
11,12,28.0,F,1,Y,1,62.75,58.0,79,Y,1.0,10
8,9,29.0,M,2,Y,1,74.00,73.0,106,N,0.0,5
21,22,29.0,M,2,N,0,71.00,70.0,101,Y,1.0,8
49,50,30.0,F,1,N,0,74.60,NaN,71,Y,1.0,9
10,11,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
39,40,30.0,M,2,Y,1,69.50,66.0,96,Y,1.0,6
44,45,30.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
14,15,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
38,39,31.0,M,2,Y,1,73.00,74.0,72,Y,1.0,9
28,29,32.0,F,1,Y,1,63.00,60.0,75,Y,1.0,8
2,3,33.0,F,1,Y,1,66.00,64.0,85,Y,1.0,7
31,32,33.0,F,1,Y,1,65.30,64.0,91,Y,1.0,7
9,10,33.0,F,1,Y,1,63.00,60.0,65,Y,1.0,8
32,33,38.0,F,1,N,0,64.00,63.0,86,Y,1.0,10
29,30,38.0,F,1,Y,1,61.50,61.0,78,Y,1.0,7
3,4,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
45,46,39.0,F,1,N,0,64.00,63.0,87,Y,1.0,10
0,1,56.0,F,1,Y,1,62.00,61.0,79,Y,1.0,7
50,51,NaN,M,2,N,0,71.00,70.0,101,Y,NaN,8

The attribute **Groupby** involves splitting the data into groups based on some criteria, applying a function to each group independently and combining the results into a data structure. df.groupby(col) returns a groupby object for values from one column while df.groupby([col1,col2]) returns a groupby object for values from multiple columns.

df.groupby(['Gender'])

In [108]:
df.groupby(['Gender'])

Size of each group

df.groupby(['Gender']).size()

df.groupby(['Gender','GenderGroup']).size()

In [110]:
df.groupby(['Gender','GenderGroup']).size()

Gender  GenderGroup
F       1              26
M       2              26
dtype: int64

This output indicates that we have two types of combinations.

* Case 1: Gender = F & Gender Group = 1
* Case 2: Gender = M & GenderGroup = 2.  

This validates our initial assumption that these two fields essentially portray the same information.

# Data Cleaning: handle with missing data

Before getting started to work with your data, it's a good practice to observe it thoroughly to identify missing values and handle them accordingly.

When reading a dataset using Pandas, there is a set of values including 'NA', 'NULL', and 'NaN' that are taken by default to represent a missing value.  The full list of default missing value codes is in the '`read_csv`' documentation [here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html).  This document also explains how to change the way that '`read_csv`' decides whether a variable's value is missing.

Pandas has functions called `isnull` and `notnull` that can be used to identify where the missing and non-missing values are located in a data frame.  

Below we use these functions to count the number of missing and non-missing values in each variable of the datasetr.

In [112]:
print("NOT Null Data")
print(df.notnull())

print("\n\nNull Data")

print(df.isnull())

NOT Null Data
      ID    Age  Gender  GenderGroup  Glasses  GlassesGroup  Height  Wingspan  \
0   True   True    True         True     True          True    True      True
1   True   True    True         True     True          True    True      True
2   True   True    True         True     True          True    True      True
3   True   True    True         True     True          True    True      True
4   True   True    True         True     True          True    True      True
5   True   True    True         True     True          True    True      True
6   True   True    True         True     True          True    True      True
7   True   True    True         True     True          True    True      True
8   True   True    True         True     True          True    True      True
9   True   True    True         True     True          True    True      True
10  True   True    True         True     True          True    True      True
11  True   True    True         True     True          True    True      True
12  True   True    True         True     True          True    True      True
13  True   True    True         True     True          True    True      True
14  True   True    True         True     True          True    True      True
15  True   True    True         True     True          True    True      True
16  True   True    True         True     True          True    True      True
17  True   True    True         True     True          True    True      True
18  True   True    True         True     True          True    True      True
19  True   True    True         True     True          True    True      True
20  True   True    True         True     True          True    True      True
21  True   True    True         True     True          True    True      True
22  True   True    True         True     True          True    True      True
23  True   True    True         True     True          True    True      True
24  True   True    True         True     True          True    True      True
25  True   True    True         True     True          True    True      True
26  True   True    True         True     True          True    True      True
27  True   True    True         True     True          True    True      True
28  True   True    True         True     True          True    True      True
29  True   True    True         True     True          True    True      True
30  True   True    True         True     True          True    True      True
31  True   True    True         True     True          True    True      True
32  True   True    True         True     True          True    True      True
33  True   True    True         True     True          True    True      True
34  True   True    True         True     True          True    True      True
35  True   True    True         True     True          True    True      True
36  True   True    True         True     True          True    True      True
37  True   True    True         True     True          True    True      True
38  True   True    True         True     True          True    True      True
39  True   True    True         True     True          True    True      True
40  True   True    True         True     True          True    True      True
41  True   True    True         True     True          True    True      True
42  True   True    True         True     True          True    True      True
43  True   True    True         True     True          True    True      True
44  True   True    True         True     True          True    True      True
45  True   True    True         True     True          True    True      True
46  True   True    True         True     True          True    True      True
47  True   True    True         True     True          True    True      True
48  True   True    True         True     True          True    True      True
49  True   True    True         True     True          True    True     False
50  True  False    True         True     True          True    True      True
51  True   True    True         True     True          True   False      True

    CWDistance  Complete  CompleteGroup  Score
0         True      True           True   True
1         True      True           True   True
2         True      True           True   True
3         True      True           True   True
4         True      True           True   True
5         True      True           True   True
6         True      True           True   True
7         True      True           True   True
8         True      True           True   True
9         True      True           True   True
10        True      True           True   True
11        True      True           True   True
12        True      True           True   True
13        True      True           True   True
14        True      True           True   True
15        True      True           True   True
16        True      True           True   True
17        True      True           True   True
18        True      True           True   True
19        True      True           True   True
20        True      True           True   True
21        True      True           True   True
22        True      True           True   True
23        True      True           True   True
24        True      True           True   True
25        True      True           True   True
26        True      True           True   True
27        True      True           True   True
28        True      True           True   True
29        True      True           True   True
30        True      True           True   True
31        True      True           True   True
32        True      True           True   True
33        True      True           True   True
34        True      True           True   True
35        True      True           True   True
36        True      True           True   True
37        True      True           True   True
38        True      True           True   True
39        True      True           True   True
40        True      True           True   True
41        True      True           True   True
42        True      True           True   True
43        True      True           True   True
44        True      True           True   True
45        True      True           True   True
46        True      True           True   True
47        True      True           True   True
48        True      True           True   True
49        True      True           True   True
50        True      True          False   True
51        True      True           True   True


Null Data
       ID    Age  Gender  GenderGroup  Glasses  GlassesGroup  Height  \
0   False  False   False        False    False         False   False
1   False  False   False        False    False         False   False
2   False  False   False        False    False         False   False
3   False  False   False        False    False         False   False
4   False  False   False        False    False         False   False
5   False  False   False        False    False         False   False
6   False  False   False        False    False         False   False
7   False  False   False        False    False         False   False
8   False  False   False        False    False         False   False
9   False  False   False        False    False         False   False
10  False  False   False        False    False         False   False
11  False  False   False        False    False         False   False
12  False  False   False        False    False         False   False
13  False  False   False        False    False         False   False
14  False  False   False        False    False         False   False
15  False  False   False        False    False         False   False
16  False  False   False        False    False         False   False
17  False  False   False        False    False         False   False
18  False  False   False        False    False         False   False
19  False  False   False        False    False         False   False
20  False  False   False        False    False         False   False
21  False  False   False        False    False         False   False
22  False  False   False        False    False         False   False
23  False  False   False        False    False         False   False
24  False  False   False        False    False         False   False
25  False  False   False        False    False         False   False
26  False  False   False        False    False         False   False
27  False  False   False        False    False         False   False
28  False  False   False        False    False         False   False
29  False  False   False        False    False         False   False
30  False  False   False        False    False         False   False
31  False  False   False        False    False         False   False
32  False  False   False        False    False         False   False
33  False  False   False        False    False         False   False
34  False  False   False        False    False         False   False
35  False  False   False        False    False         False   False
36  False  False   False        False    False         False   False
37  False  False   False        False    False         False   False
38  False  False   False        False    False         False   False
39  False  False   False        False    False         False   False
40  False  False   False        False    False         False   False
41  False  False   False        False    False         False   False
42  False  False   False        False    False         False   False
43  False  False   False        False    False         False   False
44  False  False   False        False    False         False   False
45  False  False   False        False    False         False   False
46  False  False   False        False    False         False   False
47  False  False   False        False    False         False   False
48  False  False   False        False    False         False   False
49  False  False   False        False    False         False   False
50  False   True   False        False    False         False   False
51  False  False   False        False    False         False    True

    Wingspan  CWDistance  Complete  CompleteGroup  Score
0      False       False     False          False  False
1      False       False     False          False  False
2      False       False     False          False  False
3      False       False     False          False  False
4      False       False     False          False  False
5      False       False     False          False  False
6      False       False     False          False  False
7      False       False     False          False  False
8      False       False     False          False  False
9      False       False     False          False  False
10     False       False     False          False  False
11     False       False     False          False  False
12     False       False     False          False  False
13     False       False     False          False  False
14     False       False     False          False  False
15     False       False     False          False  False
16     False       False     False          False  False
17     False       False     False          False  False
18     False       False     False          False  False
19     False       False     False          False  False
20     False       False     False          False  False
21     False       False     False          False  False
22     False       False     False          False  False
23     False       False     False          False  False
24     False       False     False          False  False
25     False       False     False          False  False
26     False       False     False          False  False
27     False       False     False          False  False
28     False       False     False          False  False
29     False       False     False          False  False
30     False       False     False          False  False
31     False       False     False          False  False
32     False       False     False          False  False
33     False       False     False          False  False
34     False       False     False          False  False
35     False       False     False          False  False
36     False       False     False          False  False
37     False       False     False          False  False
38     False       False     False          False  False
39     False       False     False          False  False
40     False       False     False          False  False
41     False       False     False          False  False
42     False       False     False          False  False
43     False       False     False          False  False
44     False       False     False          False  False
45     False       False     False          False  False
46     False       False     False          False  False
47     False       False     False          False  False
48     False       False     False          False  False
49      True       False     False          False  False
50     False       False     False           True  False
51     False       False     False          False  False

Unfortunately, our output indicates that some of our columns contain missing values so we are no able to continue on doing analysis with those colums

In [116]:
print("NULL")
print(df.isnull().sum())
print("\n NOT NULL")
print(df.notnull().sum())

NULL
ID               0
Age              1
Gender           0
GenderGroup      0
Glasses          0
GlassesGroup     0
Height           1
Wingspan         1
CWDistance       0
Complete         0
CompleteGroup    1
Score            0
dtype: int64

 NOT NULL
ID               52
Age              51
Gender           52
GenderGroup      52
Glasses          52
GlassesGroup     52
Height           51
Wingspan         51
CWDistance       52
Complete         52
CompleteGroup    51
Score            52
dtype: int64

Now we use these functions to count the number of missing and non-missing values in a single variable in the dataset

print( df.Height.notnull().sum() )

print( pd.isnull(df.Height).sum() )

In [117]:
print( df.Height.notnull().sum() )

print( pd.isnull(df.Height).sum() )

51
1

In [118]:
# Extract all non-missing values of one of the columns into a new variable
x = df.Age.dropna().describe()
x.describe()

count     8.000000
mean     30.645922
std      16.044470
min       5.755611
25%      24.250000
50%      27.705882
75%      35.250000
max      56.000000
Name: Age, dtype: float64

# Add and eliminate columns

In some cases it is useful to create or eiminate new columns

In [119]:
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [143]:
# Add a new column with new data

# Create a column data
NewColumnData = df.Age/df.Age

# Insert that column in the data frame
df.insert(12, "ColumnInserted", NewColumnData, True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,ColumnInserted,ColumnInserted,ColumnInserted,ColumnInserted,ColumnInserted
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,1.0,1.0,1.0,1.0,1.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,1.0,1.0,1.0,1.0,1.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,1.0,1.0,1.0,1.0,1.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,1.0,1.0,1.0,1.0,1.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,1.0,1.0,1.0,1.0,1.0

In [144]:
df.head()
# # Eliminate inserted column
#df.drop("ColumnInserted", axis=1, inplace = True)
#df.drop(columns=['ColumnInserted'], inplace = True)
# # Remove three columns as index base
df.drop(df.columns[[12]], axis = 1, inplace = True)
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [145]:
# # Add new column derived from existing columns
#
# # The new column is a function of another column
df["AgeInMonths"] = df["Age"] * 12
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,AgeInMonths
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,672.0
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,312.0
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,396.0
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,468.0
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,324.0

In [146]:
# # Eliminate inserted column
df.drop("AgeInMonths", axis=1, inplace = True)
#
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [156]:
# Add a new column with text labels reflecting the code's meaning

df["GenderGroupNew"] = df.GenderGroup.replace({1: "Female", 2: "Male"})

# Show the first 5 rows of the created data frame
df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score,GenderGroupNew
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7,Female
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8,Female
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7,Female
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10,Female
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4,Male

In [157]:
## Eliminate inserted column
df.head()
# df.drop("GenderGroupNew", axis=1, inplace = True)
df.drop(['GenderGroupNew'],axis='columns',inplace=True)

df.head()

,ID,Age,Gender,GenderGroup,Glasses,GlassesGroup,Height,Wingspan,CWDistance,Complete,CompleteGroup,Score
0,1,56.0,F,1,Y,1,62.0,61.0,79,Y,1.0,7
1,2,26.0,F,1,Y,1,62.0,60.0,70,Y,1.0,8
2,3,33.0,F,1,Y,1,66.0,64.0,85,Y,1.0,7
3,4,39.0,F,1,N,0,64.0,63.0,87,Y,1.0,10
4,5,27.0,M,2,N,0,73.0,75.0,72,N,0.0,4

In [166]:
## Add a new column with strata based on these cut points
#
## Create a column data
NewColumnData = df.Age/df.Age
#
## Insert that column in the data frame
df.insert(1, "ColumnStrata", NewColumnData, True)
#
df["ColumnStrata"] = pd.cut(df.Height, [60., 63., 66., 69., 72., 75., 78.])
#
## Show the first 5 rows of the created data frame
df.head()

,Age,ColumnStrata,Gender,Glasses,Height,Wingspan,CWDistance,Complete,Score
0,56.0,"(60.0, 63.0]",F,Y,62.0,61.0,79,Y,7
1,26.0,"(60.0, 63.0]",F,Y,62.0,60.0,70,Y,8
2,33.0,"(63.0, 66.0]",F,Y,66.0,64.0,85,Y,7
3,39.0,"(63.0, 66.0]",F,N,64.0,63.0,87,Y,10
4,27.0,"(72.0, 75.0]",M,N,73.0,75.0,72,N,4

In [167]:
## Eliminate inserted column
df.drop("ColumnStrata", axis=1, inplace = True)
#
df.head()

    Age Gender Glasses  Height  Wingspan  CWDistance Complete  Score
0  56.0      F       Y    62.0      61.0          79        Y      7
1  26.0      F       Y    62.0      60.0          70        Y      8
2  33.0      F       Y    66.0      64.0          85        Y      7
3  39.0      F       N    64.0      63.0          87        Y     10
4  27.0      M       N    73.0      75.0          72        N      4

In [ ]:
# Drop several "unused" columns
vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
df.drop(vars, axis=1, inplace = True)
df.head()

# Add and eliminate rows

In some cases it is requiered to add new observations (rows) to the data set

In [171]:
# Print tail
df.tail()

     Age Gender Glasses  Height  Wingspan  CWDistance Complete  Score
47  24.0      M       N    79.5      75.0          82        N      8
48  28.0      M       N    77.8      76.0          99        Y      9
49  30.0      F       N    74.6       NaN          71        Y      9
50   NaN      M       N    71.0      70.0         101        Y      8
51  27.0      M       N     NaN      71.5         103        Y     10

In [176]:
#df.loc[len(df.index)] = [26, 24, 'F', 1, 'Y', 1, 66, 'NaN', 68, 'N', 0, 3]
df.loc[len(df.index)] = [24, 'F','Y', 66, 'NaN', 68, 'N', 3]
#
df.tail()

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
48  28.0      M       N    77.8     76.0          99        Y      9
49  30.0      F       N    74.6      NaN          71        Y      9
50   NaN      M       N    71.0     70.0         101        Y      8
51  27.0      M       N     NaN     71.5         103        Y     10
52  24.0      F       Y    66.0      NaN          68        N      3

In [178]:
## Eliminate inserted row
df.drop([52], inplace = True )
#
df.tail()

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
47  24.0      M       N    79.5     75.0          82        N      8
48  28.0      M       N    77.8     76.0          99        Y      9
49  30.0      F       N    74.6      NaN          71        Y      9
50   NaN      M       N    71.0     70.0         101        Y      8
51  27.0      M       N     NaN     71.5         103        Y     10

# Cleaning your data: drop out unused columns and/or drop out rows with any missing values

In [186]:
# Drop unused columns
#vars = ["ID", "GenderGroup", "GlassesGroup", "CompleteGroup"]
#df.drop(vars, axis=1, inplace = True)

vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars]

# Drop rows with any missing values
df = df.dropna()
# Drop unused columns and drop rows with any missing values
vars = ["Age", "Gender", "Glasses", "Height", "Wingspan", "CWDistance", "Complete", "Score"]
df = df[vars].dropna()

df

     Age Gender Glasses  Height Wingspan  CWDistance Complete  Score
0   56.0      F       Y   62.00     61.0          79        Y      7
1   26.0      F       Y   62.00     60.0          70        Y      8
2   33.0      F       Y   66.00     64.0          85        Y      7
3   39.0      F       N   64.00     63.0          87        Y     10
4   27.0      M       N   73.00     75.0          72        N      4
5   24.0      M       N   75.00     71.0          81        N      3
6   28.0      M       N   75.00     76.0         107        Y     10
7   22.0      F       N   65.00     62.0          98        Y      9
8   29.0      M       Y   74.00     73.0         106        N      5
9   33.0      F       Y   63.00     60.0          65        Y      8
10  30.0      M       Y   69.50     66.0          96        Y      6
11  28.0      F       Y   62.75     58.0          79        Y     10
12  25.0      F       Y   65.00     64.5          92        Y      6
13  23.0      F       N   61.50     57.5          66        Y      4
14  31.0      M       Y   73.00     74.0          72        Y      9
15  26.0      M       Y   71.00     72.0         115        Y      6
16  26.0      F       N   61.50     59.5          90        N     10
17  27.0      M       N   66.00     66.0          74        Y      5
18  23.0      M       Y   70.00     69.0          64        Y      3
19  24.0      F       Y   68.00     66.0          85        Y      8
20  23.0      M       Y   69.00     67.0          66        N      2
21  29.0      M       N   71.00     70.0         101        Y      8
22  25.0      M       N   70.00     68.0          82        Y      4
23  26.0      M       N   69.00     71.0          63        Y      5
24  23.0      F       Y   65.00     63.0          67        N      3
25  28.0      M       N   75.00     76.0         111        Y     10
26  24.0      M       N   78.40     71.0          92        Y      7
27  25.0      M       Y   76.00     73.0         107        Y      8
29  38.0      F       Y   61.50     61.0          78        Y      7
30  27.0      F       Y   62.00     60.0          72        Y      8
31  33.0      F       Y   65.30     64.0          91        Y      7
32  38.0      F       N   64.00     63.0          86        Y     10
33  27.0      M       N   77.00     75.0         100        Y      8
34  24.0      F       N   67.80     62.0          98        Y      9
35  27.0      M       N   68.00     66.0          74        Y      5
36  25.0      F       Y   65.00     64.5          92        Y      6
37  26.0      F       N   61.50     59.5          90        Y      9
38  31.0      M       Y   73.00     74.0          72        Y      9
39  30.0      M       Y   69.50     66.0          96        Y      6
40  23.0      F       N   70.40     71.0          66        Y      4
41  26.0      M       Y   73.50     72.0         115        Y      6
42  28.0      F       Y   72.50     72.0          81        Y     10
43  26.0      F       Y   72.00     72.0          92        Y      8
44  30.0      F       Y   66.00     64.0          85        Y      7
45  39.0      F       N   64.00     63.0          87        Y     10
46  27.0      M       N   78.00     75.0          72        N      7
47  24.0      M       N   79.50     75.0          82        N      8
48  28.0      M       N   77.80     76.0          99        Y      9

# Final remarks


- The understanding of your dataset is essential
    - Number of observations
    - Variables
    - Data types: numerical or categorial
    - What are my variables of interest

- There are several ways to do the same thing

- Cleaning your dataset (dropping out rows with any missing values) is a good practice

- The **Pandas** library provides fancy, high-performance, easy-to-use data structures and data analysis tools

# Activity: work with the iris dataset

Repeat this tutorial with the iris data set and respond to the following inquiries

1. Calculate the statistical summary for each quantitative variables. Explain the results
    - Identify the name of each column
    - Identify the type of each column
    - Minimum, maximum, mean, average, median, standar deviation
    
    
2. Are there missing data? If so, create a new dataset containing only the rows with the non-missing data


3. Create a new dataset containing only the petal width and length and the type of Flower


4. Create a new dataset containing only the setal width and length and the type of Flower


5. Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column

In [1]:
# Define where you are running the code: colab or local
RunInColab          = True     # (False: no  | True: yes)

# If running in colab:
if RunInColab:
    # Mount your google drive in google colab
    from google.colab import drive
    drive.mount('/content/drive')

    # Find location
    #!pwd
    #!ls
    #!ls "/content/drive/My Drive/Colab Notebooks/MachineLearningWithPython/"

    # Define path del proyecto
    Ruta            = "/content/drive/My Drive/TC1002S/NotebooksProfessor/"

else:
    # Define path del proyecto
    Ruta            = "nop"

Mounted at /content/drive

In [36]:
# url string that hosts our .csv file
urlnew = Ruta + "iris.csv"
print(urlnew)
# Read the .csv file and store it as a pandas Data Frame

di = pd.read_csv(urlnew)

/content/drive/My Drive/TC1002S/NotebooksProfessor/iris.csv

# 1.-Ejercicio

In [11]:
print(di.columns)

Index(['sepal.length', 'sepal.width', 'petal.length', 'petal.width',
       'variety'],
      dtype='object')

In [13]:
print(di.dtypes)

sepal.length    float64
sepal.width     float64
petal.length    float64
petal.width     float64
variety          object
dtype: object

In [32]:
di.describe()

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

# 2.-Ejercicio

In [25]:
print("NULL")
print(di.isnull().sum())
print("\n NOT NULL")
print(di.notnull().sum())

NULL
petal.length    0
petal.width     0
variety         0
dtype: int64

 NOT NULL
petal.length    150
petal.width     150
variety         150
dtype: int64

### No hay datos faltantes en el archivo

### 3.-Create a new dataset containing only the petal width and length and the type of Flower

In [33]:
## Eliminate inserted column
di.head()
# df.drop("GenderGroupNew", axis=1, inplace = True)
di.drop(['sepal.width'],axis='columns',inplace=True)
di.drop(['sepal.length'],axis='columns',inplace=True)

di.head()

   petal.length  petal.width variety
0           1.4          0.2  Setosa
1           1.4          0.2  Setosa
2           1.3          0.2  Setosa
3           1.5          0.2  Setosa
4           1.4          0.2  Setosa

### 4.-Create a new dataset containing only the setal width and length and the type of Flower

In [35]:
## Eliminate inserted column
di.head()
# df.drop("GenderGroupNew", axis=1, inplace = True)
di.drop(['petal.width'],axis='columns',inplace=True)
di.drop(['petal.length'],axis='columns',inplace=True)

di.head()

   sepal.length  sepal.width variety
0           5.1          3.5  Setosa
1           4.9          3.0  Setosa
2           4.7          3.2  Setosa
3           4.6          3.1  Setosa
4           5.0          3.6  Setosa

### 5.-Create a new dataset containing the setal width and length and the type of Flower encoded as a categorical numerical column

In [37]:
from sklearn.preprocessing import LabelEncoder

# Seleccionar solo las columnas requeridas
new_df = di[['sepal.width', 'sepal.length', 'variety']]

# Convertir la columna 'variety' en valores numéricos usando LabelEncoder
label_encoder = LabelEncoder()
new_df['variety'] = label_encoder.fit_transform(new_df['variety'])

# Mostrar las primeras filas del nuevo dataset
print(new_df.head())

   sepal.width  sepal.length  variety
0          3.5           5.1        0
1          3.0           4.9        0
2          3.2           4.7        0
3          3.1           4.6        0
4          3.6           5.0        0

<ipython-input-37-5c20cdebc76b>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['variety'] = label_encoder.fit_transform(new_df['variety'])